/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDnsCheckRouteImport } from './routes/api/public/dns-check'
import { Route as ApiPublicCodeLoginRouteImport } from './routes/api/public/code-login'
import { Route as ApiPublicActivateRouteImport } from './routes/api/public/activate'

const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDnsCheckRoute = ApiPublicDnsCheckRouteImport.update({
  id: '/api/public/dns-check',
  path: '/api/public/dns-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCodeLoginRoute = ApiPublicCodeLoginRouteImport.update({
  id: '/api/public/code-login',
  path: '/api/public/code-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActivateRoute = ApiPublicActivateRouteImport.update({
  id: '/api/public/activate',
  path: '/api/public/activate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dns': typeof DnsRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/code-login': typeof ApiPublicCodeLoginRoute
  '/api/public/dns-check': typeof ApiPublicDnsCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dns': typeof DnsRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/code-login': typeof ApiPublicCodeLoginRoute
  '/api/public/dns-check': typeof ApiPublicDnsCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dns': typeof DnsRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/code-login': typeof ApiPublicCodeLoginRoute
  '/api/public/dns-check': typeof ApiPublicDnsCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dns'
    | '/api/public/activate'
    | '/api/public/code-login'
    | '/api/public/dns-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dns'
    | '/api/public/activate'
    | '/api/public/code-login'
    | '/api/public/dns-check'
  id:
    | '__root__'
    | '/'
    | '/dns'
    | '/api/public/activate'
    | '/api/public/code-login'
    | '/api/public/dns-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DnsRoute: typeof DnsRoute
  ApiPublicActivateRoute: typeof ApiPublicActivateRoute
  ApiPublicCodeLoginRoute: typeof ApiPublicCodeLoginRoute
  ApiPublicDnsCheckRoute: typeof ApiPublicDnsCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dns-check': {
      id: '/api/public/dns-check'
      path: '/api/public/dns-check'
      fullPath: '/api/public/dns-check'
      preLoaderRoute: typeof ApiPublicDnsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/code-login': {
      id: '/api/public/code-login'
      path: '/api/public/code-login'
      fullPath: '/api/public/code-login'
      preLoaderRoute: typeof ApiPublicCodeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activate': {
      id: '/api/public/activate'
      path: '/api/public/activate'
      fullPath: '/api/public/activate'
      preLoaderRoute: typeof ApiPublicActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DnsRoute: DnsRoute,
  ApiPublicActivateRoute: ApiPublicActivateRoute,
  ApiPublicCodeLoginRoute: ApiPublicCodeLoginRoute,
  ApiPublicDnsCheckRoute: ApiPublicDnsCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
